### ISSUE TITLE
header.jsx / footer.jsx not rendered

### ISSUE THREAD

**Issue by felixdorner** [Automattic/Picard#49]
Hey, I am pretty new to React and my question might be a little bit noobish:
There are JSX files for the header and footer but it seems that they are not rendered to an elementByID? Is there a reason for not doing so?

**Comment by jacklenox** [comment]
No worries at all about noob questions. :smile: And you're right, the simple answer is that inclusion of the header and footer JSX files is a todo (this should be marked out in the files themselves).

The entire theme is rendered just once in [picard.jsx](https://github.com/Automattic/Picard/blob/master/components/picard.jsx#L11-L16). So even if the header and footer components were used, they would be included in the overall theme rather than rendered separately.
