### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by dmr** [Automattic/Picard#52]
I really like this project, thank you.

The Readme states

```
"Please note, it is STRONGLY recommended that this theme is not used in any production environment. It is purely for educational and testing purposes."
```

and I was wondering if this changed since the beginning of this project.

Is anyone here using it in production?
I read that wordpress.com is moving towards WP-API and react and maybe something like this is happening in the wordpress theme community also.

Also, serverside rendering in picard, did anyone already manage to integrate it?

**Comment by cr101** [comment]
Integrating serverside rendering is essential because using the WordPress API to fetch the data for the theme doesn’t really make sense as the WP API is self consuming (the end points live on the same server  the theme is served from) and it can save the round trip request from the browser to the server and then back down to the browser again.

**Comment by dmr** [comment]
Are there any projects/themes you guys use instead of picard?

**Comment by cr101** [comment]
@dmr Try [Foxhound](https://github.com/ryelle/Foxhound) which was recently featured on [WPTavern](https://wptavern.com/foxhound-is-the-first-rest-api-powered-theme-on-wordpress-org)

**Comment by dmr** [comment]
Thank you for the hint, I'll give it a try
